[build]
  command = "node scripts/netlify-build.js"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

# 构建前执行数据库初始化
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # 排除 API 路由和 Netlify 函数
  condition = { "!path" = "/api/*", "!path" = "/.netlify/*" }