[build]
  command = "node scripts/netlify-build.js"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 构建前执行数据库初始化
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # 排除 API 路由和 Netlify 函数
  condition = { "!path" = ["/api/*", "/.netlify/*"] }

# 为 API 路由设置特殊处理
[[redirects]]
  from = "/api/cron"
  to = "/.netlify/functions/cron-job"
  status = 200
  force = true