name: 定时任务触发器

on:
  schedule:
    # 每5分钟执行一次 (UTC时间)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    
    steps:
    - name: 触发定时任务
      run: |
        echo "正在触发定时任务执行..."
        curl -X GET "${{ secrets.VERCEL_CRON_URL }}" \
          --max-time 30 \
          --retry 3 \
          --retry-delay 5
        echo "定时任务触发完成"
    
    - name: 记录执行时间
      run: |
        echo "执行时间: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo "北京时间: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S CST')"